### ISSUE TITLE
API - Refine Export Functionality

### ISSUE THREAD

**Issue by somni1oquist** [nitishragu12/Capstone-Project#34]
Refine export functionality to conform to the new requirements i.e. instruction box.

Mainly output the data from Gemini API response.

For the detailed flow please refer to the picture below:
![Image](https://github.com/user-attachments/assets/e53a0247-6076-4b09-9c75-4eb5f277b34a)

**Comment by Halffancyy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API - Refine Export Functionality](https://trello.com/c/5AWu3tr0/40-api-refine-export-functionality)
