### ISSUE TITLE
Docs - Meeting Minutes

### ISSUE THREAD

**Issue by somni1oquist** [nitishragu12/Capstone-Project#93]
8th August: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/EWsZMAhNY4hAqLwbZDXRxw0BnzW2SDSd0ouLYKunZHMHUg?e=QNu57f

15th August: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/ETzclG4xlY1AkkEe_RGnoLYBnCRZM7oU9-XQvVl62NLYIQ?e=Ju8MSt

22nd August: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/EaKcACuJiChJv49dyDQpoW0BcSMsVI2fSe4YqLd0yYmyVQ?e=12pZzk

29th August: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/EfdZq11BAo5CoJ7c4Qib4cgBU0SoQFpWBhpSudwatW6ocw?e=yXW2Kp

12th September: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/ERjalMMZZ0lKm32Ke0xDN4UBok74bK0WE-7pS3Rbs2Cgog?e=JaZaan

26th September: https://uniwa-my.sharepoint.com/:b:/g/personal/23926903_student_uwa_edu_au/EafDXaFTLQ9JpoeAwf43FwwBtrfk_02w0NYCZoIAoEjtVQ?e=s6ZP19

**Comment by Halffancyy** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [API - Endpoint for mutation](https://trello.com/c/UB0ATqBB/42-api-endpoint-for-mutation)
